### ISSUE TITLE
unable to find element 

### ISSUE THREAD

**Issue by SrinivasanTarget** [AppiumTestDistribution/appium-wait-plugin#33]
`TypeError: Cannot read properties of undefined (reading 'element-wait')`

full gist is [here](https://gist.github.com/omprakashchavan01/41151a879423a0478c9fbd7e64a1aa58)

Appium v2.0.0-beta.42
[Appium] Available drivers:
[Appium]   - uiautomator2@2.4.6 (automationName 'UiAutomator2')
[Appium] Available plugins:
[Appium]   - element-wait@1.0.2 (ACTIVE)

**Comment by SrinivasanTarget** [comment]
All good in mac - https://gist.github.com/SrinivasanTarget/05ee2650168ef8a358b6935a91f0cae6

**Comment by SrinivasanTarget** [comment]
@omprakashchavan01

**Comment by omprakashchavan01** [comment]
I have used Windows.
For UI elements, using Page Factory.

**Comment by saikrishna321** [comment]
@omprakashchavan01 We found the issue. Will fix and release a version

**Comment by saikrishna321** [comment]
@omprakashchavan01 Can you try with vesion 1.0.3

**Comment by omprakashchavan01** [comment]
Tried and I got below error while starting the appium server. Note that the same issue is observed for Appium beta 42 and 43.

```
C:\Users\ompra>appium --use-plugins=element-wait
[Appium] Attempting to load plugin element-wait...
[debug] [Appium] Requiring plugin at C:\Users\ompra\.appium\node_modules\appium-wait-plugin
[Appium] Could not load plugin 'element-wait', so it will not be available. Error in loading the plugin was: Cannot find module '@appium/support'
[Appium] Require stack:
[Appium] - C:\Users\ompra\.appium\node_modules\appium-wait-plugin\lib\logger.js
[Appium] - C:\Users\ompra\.appium\node_modules\appium-wait-plugin\lib\element.js
[Appium] - C:\Users\ompra\.appium\node_modules\appium-wait-plugin\lib\plugin.js
[Appium] - C:\Users\ompra\.appium\node_modules\appium-wait-plugin\lib\index.js
[Appium] - C:\Users\ompra\AppData\Roaming\npm\node_modules\appium\build\lib\extension\extension-config.js
[Appium] - C:\Users\ompra\AppData\Roaming\npm\node_modules\appium\build\lib\cli\extension-command.js
[Appium] - C:\Users\ompra\AppData\Roaming\npm\node_modules\appium\build\lib\cli\driver-command.js
[Appium] - C:\Users\ompra\AppData\Roaming\npm\node_modules\appium\build\lib\cli\extension.js
[Appium] - C:\Users\ompra\AppData\Roaming\npm\node_modules\appium\build\lib\main.js
[Appium] - C:\Users\ompra\AppData\Roaming\npm\node_modules\appium\index.js
[debug] [Appium] Error: Cannot find module '@appium/support'
[debug] [Appium] Require stack:
[debug] [Appium] - C:\Users\ompra\.appium\node_modules\appium-wait-plugin\lib\logger.js
[debug] [Appium] - C:\Users\ompra\.appium\node_modules\appium-wait-plugin\lib\element.js
[debug] [Appium] - C:\Users\ompra\.appium\node_modules\appium-wait-plugin\lib\plugin.js
[debug] [Appium] - C:\Users\ompra\.appium\node_modules\appium-wait-plugin\lib\index.js
[debug] [Appium] - C:\Users\ompra\AppData\Roaming\npm\node_modules\appium\build\lib\extension\extension-config.js
[debug] [Appium] - C:\Users\ompra\AppData\Roaming\npm\node_modules\appium\build\lib\cli\extension-command.js
[debug] [Appium] - C:\Users\ompra\AppData\Roaming\npm\node_modules\appium\build\lib\cli\driver-command.js
[debug] [Appium] - C:\Users\ompra\AppData\Roaming\npm\node_modules\appium\build\lib\cli\extension.js
[debug] [Appium] - C:\Users\ompra\AppData\Roaming\npm\node_modules\appium\build\lib\main.js
[debug] [Appium] - C:\Users\ompra\AppData\Roaming\npm\node_modules\appium\index.js
[debug] [Appium]     at Function.Module._resolveFilename (node:internal/modules/cjs/loader:933:15)
[debug] [Appium]     at Function.Module._load (node:internal/modules/cjs/loader:778:27)
[debug] [Appium]     at Module.require (node:internal/modules/cjs/loader:1005:19)
[debug] [Appium]     at require (node:internal/modules/cjs/helpers:102:18)
[debug] [Appium]     at Object.<anonymous> (C:\Users\ompra\.appium\node_modules\appium-wait-plugin\lib\logger.js:3:16)
[debug] [Appium]     at Module._compile (node:internal/modules/cjs/loader:1105:14)
[debug] [Appium]     at Object.Module._extensions..js (node:internal/modules/cjs/loader:1159:10)
[debug] [Appium]     at Module.load (node:internal/modules/cjs/loader:981:32)
[debug] [Appium]     at Function.Module._load (node:internal/modules/cjs/loader:822:12)
[debug] [Appium]     at Module.require (node:internal/modules/cjs/loader:1005:19)
[debug] [Appium]     at require (node:internal/modules/cjs/helpers:102:18)
[debug] [Appium]     at Object.<anonymous> (C:\Users\ompra\.appium\node_modules\appium-wait-plugin\lib\element.js:16:34)
[debug] [Appium]     at Module._compile (node:internal/modules/cjs/loader:1105:14)
[debug] [Appium]     at Object.Module._extensions..js (node:internal/modules/cjs/loader:1159:10)
[debug] [Appium]     at Module.load (node:internal/modules/cjs/loader:981:32)
[debug] [Appium]     at Function.Module._load (node:internal/modules/cjs/loader:822:12)
[debug] [Appium]     at Module.require (node:internal/modules/cjs/loader:1005:19)
[debug] [Appium]     at require (node:internal/modules/cjs/helpers:102:18)
[debug] [Appium]     at Object.<anonymous> (C:\Users\ompra\.appium\node_modules\appium-wait-plugin\lib\plugin.js:16:19)
[debug] [Appium]     at Module._compile (node:internal/modules/cjs/loader:1105:14)
[debug] [Appium]     at Object.Module._extensions..js (node:internal/modules/cjs/loader:1159:10)
[debug] [Appium]     at Module.load (node:internal/modules/cjs/loader:981:32)
[Appium] Welcome to Appium v2.0.0-beta.42
[Appium] Non-default server args:
[Appium] {
[Appium]   usePlugins: [
[Appium]     'element-wait'
[Appium]   ]
[Appium] }
[Appium] Attempting to load driver uiautomator2...
[debug] [Appium] Requiring driver at C:\Users\ompra\.appium\node_modules\appium-uiautomator2-driver
[Appium] Appium REST http interface listener started on 0.0.0.0:4723
[Appium] Available drivers:
[Appium]   - uiautomator2@2.4.6 (automationName 'UiAutomator2')
[Appium] Available plugins:
[Appium]   - element-wait@1.0.3
[Appium] No plugins activated. Use the --use-plugins flag with names of plugins to activate
```

**Comment by saikrishna321** [comment]
@omprakashchavan01 Can you check with version v1.0.4.

**Comment by omprakashchavan01** [comment]
Working now. Thank you.
