### ISSUE TITLE
find elements not working for iOS platform it wait for 40 sec

### ISSUE THREAD

**Issue by sushilpawar12** [AppiumTestDistribution/appium-wait-plugin#72]
[debug] [XCUITestDriver@1a9e (5f06c4da)] Calling AppiumDriver.findElements() with args: ["xpath","//XCUIElementTypeButton[contains(@name,'Heart') and contains(@name,'selected')]","5f06c4da-6fc1-486b-b694-909b33b49e47"]
[AppiumDriver@1acc] Plugins which can handle cmd 'findElements': element-wait
[AppiumDriver@1acc] Plugin element-wait is now handling cmd 'findElements'
[AppiumDriver@1acc] Executing default handling behavior for command 'findElements'
[debug] [XCUITestDriver@1a9e (5f06c4da)] Executing command 'findElements'
[debug] [XCUITestDriver@1a9e (5f06c4da)] Valid locator strategies for this request: xpath, id, name, class name, -ios predicate string, -ios class chain, accessibility id, css selector
[debug] [XCUITestDriver@1a9e (5f06c4da)] Waiting up to 40000 ms for condition
[debug] [XCUITestDriver@1a9e (5f06c4da)] Matched '/elements' to command name 'findElements'
[debug] [XCUITestDriver@1a9e (5f06c4da)] Proxying [POST /elements] to [POST http://127.0.0.1:8100/session/BF10DD05-C5BF-413B-8889-FF84AB42A317/elements] with body: {"using":"xpath","value":"//XCUIElementTypeButton[contains(@name,'Heart') and contains(@name,'selected')]"}
[debug] [XCUITestDriver@1a9e (5f06c4da)] Got response with status 200: {"value":[],"sessionId":"BF10DD05-C5BF-413B-8889-FF84AB42A317"}
[debug] [XCUITestDriver@1a9e (5f06c4da)] Waited for 547 ms so far
[debug] [XCUITestDriver@1a9e (5f06c4da)] Matched '/elements' to command name 'findElements'
[debug] [XCUITestDriver@1a9e (5f06c4da)] Proxying [POST /elements] to [POST http://127.0.0.1:8100/session/BF10DD05-C5BF-413B-8889-FF84AB42A317/elements] with body: {"using":"xpath","value":"//XCUIElementTypeButton[contains(@name,'Heart') and contains(@name,'selected')]"}
[debug] [XCUITestDriver@1a9e (5f06c4da)] Got response with status 200: {"value":[],"sessionId":"BF10DD05-C5BF-413B-8889-FF84AB42A317"}
[debug] [XCUITestDriver@1a9e (5f06c4da)] Waited for 1592 ms so far

**Appium v - 2.0.0-beta.65 , xcuitest@4.24.2 , element-wait@1.3.0**

**Comment by saikrishna321** [comment]
What is the error? Please give full logs

**Comment by sushilpawar12** [comment]
when we are using iOS predicate & iOS class chain locator to find element or find elements then wait plugin is not working @saikrishna321

**Comment by saikrishna321** [comment]
Give full logs please to check whats wrong. @sushilpawar12

**Comment by sushilpawar12** [comment]
**Same error after updating to new version - Appium v - 2.0.0-beta.66 , xcuitest@4.24.2 , element-wait@1.3.0**

[debug] [XCUITestDriver@9d70 (f47cc5ae)] Calling AppiumDriver.findElement() with args: ["xpath","//XCUIElementTypeButton[contains(@name,'Don') and contains(@name,'Allow')]","f47cc5ae-d8d0-46f6-ab22-74b6f4a51965"]
[AppiumDriver@85a4] Plugins which can handle cmd 'findElement': element-wait
[AppiumDriver@85a4] Plugin element-wait is now handling cmd 'findElement'
[wait-plugin] Timeout properties set for session f47cc5ae-d8d0-46f6-ab22-74b6f4a51965 is {"timeout":10000,"intervalBetweenAttempts":500,"overrideTimeout":false} ms
Session INfor XCUITest
[AppiumDriver@85a4] Command 'findElement' was *not* handled by the following behaviours or plugins, even though they were registered to handle it: ["default"]. The command *was* handled by these: ["element-wait"].
[debug] [XCUITestDriver@9d70 (f47cc5ae)] Encountered internal error running command: TypeError: Cannot read properties of undefined (reading 'jwproxy')
[debug] [XCUITestDriver@9d70 (f47cc5ae)]     at sessionInfo (/Users/sushilpawar/.appium/node_modules/appium-wait-plugin/lib/element.js:141:52)
[debug] [XCUITestDriver@9d70 (f47cc5ae)]     at /Users/sushilpawar/.appium/node_modules/appium-wait-plugin/lib/element.js:33:36
[debug] [XCUITestDriver@9d70 (f47cc5ae)]     at Generator.next (<anonymous>)
[debug] [XCUITestDriver@9d70 (f47cc5ae)]     at /Users/sushilpawar/.appium/node_modules/appium-wait-plugin/lib/element.js:8:71
[debug] [XCUITestDriver@9d70 (f47cc5ae)]     at new Promise (<anonymous>)
[debug] [XCUITestDriver@9d70 (f47cc5ae)]     at __awaiter (/Users/sushilpawar/.appium/node_modules/appium-wait-plugin/lib/element.js:4:12)
[debug] [XCUITestDriver@9d70 (f47cc5ae)]     at find (/Users/sushilpawar/.appium/node_modules/appium-wait-plugin/lib/element.js:22:12)
[debug] [XCUITestDriver@9d70 (f47cc5ae)]     at WaitCommandPlugin.<anonymous> (/Users/sushilpawar/.appium/node_modules/appium-wait-plugin/lib/plugin.js:36:38)
[debug] [XCUITestDriver@9d70 (f47cc5ae)]     at Generator.next (<anonymous>)
[debug] [XCUITestDriver@9d70 (f47cc5ae)]     at /Users/sushilpawar/.appium/node_modules/appium-wait-plugin/lib/plugin.js:8:71

**Comment by sushilpawar12** [comment]
### Hi @saikrishna321 
Sorry for the delay .. 
While using find elements in framework again it find elements till 40 seconds
---------
[HTTP] {"using":"xpath","value":"//XCUIElementTypeButton[contains(@name,'Heart') and contains(@name,'selected')]"}
[debug] [XCUITestDriver@d475 (2b09d1e1)] Calling AppiumDriver.findElements() with args: ["xpath","//XCUIElementTypeButton[contains(@name,'Heart') and contains(@name,'selected')]","2b09d1e1-1b3f-42d3-bc5f-8e20909aac16"]
[AppiumDriver@2b6d] Plugins which can handle cmd 'findElements': element-wait
[AppiumDriver@2b6d] Plugin element-wait is now handling cmd 'findElements'
[AppiumDriver@2b6d] Executing default handling behavior for command 'findElements'
[debug] [XCUITestDriver@d475 (2b09d1e1)] Executing command 'findElements'
[debug] [XCUITestDriver@d475 (2b09d1e1)] Valid locator strategies for this request: xpath, id, name, class name, -ios predicate string, -ios class chain, accessibility id, css selector
[debug] [XCUITestDriver@d475 (2b09d1e1)] Waiting up to 40000 ms for condition
[debug] [XCUITestDriver@d475 (2b09d1e1)] Matched '/elements' to command name 'findElements'
[debug] [XCUITestDriver@d475 (2b09d1e1)] Proxying [POST /elements] to [POST http://127.0.0.1:8100/session/89AAE85B-1E15-43F3-A1FA-48B6E31BC8E4/elements] with body: {"using":"xpath","value":"//XCUIElementTypeButton[contains(@name,'Heart') and contains(@name,'selected')]"}
[debug] [XCUITestDriver@d475 (2b09d1e1)] Got response with status 200: {"value":[],"sessionId":"89AAE85B-1E15-43F3-A1FA-48B6E31BC8E4"}
[debug] [XCUITestDriver@d475 (2b09d1e1)] Waited for 470 ms so far
[debug] [XCUITestDriver@d475 (2b09d1e1)] Matched '/elements' to command name 'findElements'
[debug] [XCUITestDriver@d475 (2b09d1e1)] Proxying [POST /elements] to [POST http://127.0.0.1:8100/session/89AAE85B-1E15-43F3-A1FA-48B6E31BC8E4/elements] with body: {"using":"xpath","value":"//XCUIElementTypeButton[contains(@name,'Heart') and contains(@name,'selected')]"}
[debug] [XCUITestDriver@d475 (2b09d1e1)] Got response with status 200: {"value":[],"sessionId":"89AAE85B-1E15-43F3-A1FA-48B6E31BC8E4"}
[debug] [XCUITestDriver@d475 (2b09d1e1)] Waited for 1403 ms so far
[debug] [XCUITestDriver@d475 (2b09d1e1)] Matched '/elements' to command name 'findElements'
[debug] [XCUITestDriver@d475 (2b09d1e1)] Proxying [POST /elements] to [POST http://127.0.0.1:8100/session/89AAE85B-1E15-43F3-A1FA-48B6E31BC8E4/elements] with body: {"using":"xpath","value":"//XCUIElementTypeButton[contains(@name,'Heart') and contains(@name,'selected')]"}
[debug] [XCUITestDriver@d475 (2b09d1e1)] Got response with status 200: {"value":[],"sessionId":"89AAE85B-1E15-43F3-A1FA-48B6E31BC8E4"}
[debug] [XCUITestDriver@d475 (2b09d1e1)] Waited for 2356 ms so far
[debug] [XCUITestDriver@d475 (2b09d1e1)] Matched '/elements' to command name 'findElements'
[debug] [XCUITestDriver@d475 (2b09d1e1)] Proxying [POST /elements] to [POST http://127.0.0.1:8100/session/89AAE85B-1E15-43F3-A1FA-48B6E31BC8E4/elements] with body: {"using":"xpath","value":"//XCUIElementTypeButton[contains(@name,'Heart') and contains(@name,'selected')]"}
[debug] [XCUITestDriver@d475 (2b09d1e1)] Got response with status 200: {"value":[],"sessionId":"89AAE85B-1E15-43F3-A1FA-48B6E31BC8E4"}
[debug] [XCUITestDriver@d475 (2b09d1e1)] Waited for 3144 ms so far
[debug] [XCUITestDriver@d475 (2b09d1e1)] Matched '/elements' to command name 'findElements'
[debug] [XCUITestDriver@d475 (2b09d1e1)] Proxying [POST /elements] to [POST http://127.0.0.1:8100/session/89AAE85B-1E15-43F3-A1FA-48B6E31BC8E4/elements] with body: {"using":"xpath","value":"//XCUIElementTypeButton[contains(@name,'Heart') and contains(@name,'selected')]"}
-------------

**Appium v - 2.0.0-beta.66 , xcuitest@4.24.3 , element-wait@1.3.0**

**Comment by saikrishna321** [comment]
@sushilpawar12 This is not full logs. Please provide full server logs as gist

**Comment by sushilpawar12** [comment]
Hi @saikrishna321 
sorry for the delay . In logger file you can find text - "Please check below logs for reference" where below logs will be helpfull. 
**[op.txt](https://github.com/AppiumTestDistribution/appium-wait-plugin/files/11351933/op.txt)**

**Comment by saikrishna321** [comment]
@sushilpawar12 hard to read these logs. Please provide as gist
